### ISSUE TITLE
Possible to add class B functionality?

### ISSUE THREAD

**Issue by luukhd2** [i-Molecule/gpcr-3D-annotation#2]
Would it be possible to also evaluate class B GPCRs with the model? For example, by selecting only the generic residue pairs that class A and class B share (and masking the others). So far in my tests, input of class B GPCRs causes a crash and class A GPCRs work.

Or do you expect such a change would that require re-training of the model on a class B / combined dataset?

best,
Luuk

**Comment by i-Molecule** [comment]
Hi Luuk,

Thank you for the feedback.
I think one needs a separate model for class B GPCRs - although there are common patterns in activation mechanism, there are some peculiar distinctions as well. Therefore, class B receptors may be out of the applicability domain of the model trained on class A. 
However, there are quite a few class B GPCR structures, it is possible to collect the training dataset and apply the same approach to derive class-specific models.

Regarding the crash, most likely it is because of the matching of the residue pairs.

Regards,
Petr
